server:
  port: ${SERVER_PORT:8081}

spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
      show-sql: true
  datasource:
    url: ${MARIADB_URL:jdbc:mysql://localhost:3306/lms}
    username: ${MARIADB_USER:root}
    password: ${MARIADB_PASSWORD:rootPassword}

logging:
  level:
    org:
      springframework:
        security: DEBUG